server:
  container_name: bzk_server
  image: bazooka/server
  ports:
  - "3000:3000"
  - "3001:3001"
  volumes:
  - "/Users/jawher/temp/bazooka-home:/bazooka"
  - "/var/run/docker.sock:/var/run/docker.sock"
  environment:
  - "BZK_DOCKERSOCK=/var/run/docker.sock"
  - "BZK_API_URL=http://bzk_server:3000"
  - "BZK_SYSLOG_URL=tcp://192.168.99.100:3001"
  - "BZK_DB_URL=bzk_db:27017"
  - "BZK_NETWORK=bazookacompose"
  - "BZK_SCM_KEYFILE=/Users/jawher/.ssh/id_rsa"
  - "BZK_HOME=/Users/jawher/temp/bazooka-home/"

web:
  container_name: bzk_web
  image: bazooka/web
  ports:
  - "8000:80"
  environment:
  - "BZK_SERVER_HOST=bzk_server:3000"

db:
  container_name: bzk_db
  image: "mongo:3.1"
